package it.polimi.ingsw.am17.CommonInterfaces;

public enum MessageType {
    GET_GAMES_LIST,
    CREATE_GAME,
    JOIN_GAME,
    PICK_OFFERING_CARD,
    PICK_TRIBE_CARDS,

    UPDATE_GAME_ID,
    UPDATE_GAMES_ID_LIST,
    UPDATE_ERA,
    UPDATE_PLAYER_STACK,
    UPDATE_OFFERING_CARDS,
    UPDATE_TRIBES_CARDS,
    UPDATE_BUILDING_CARDS
}
